# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import modules.web.cms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=modules.web.cms.models.new_person_pk, max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
